### ISSUE TITLE
请问

### ISSUE THREAD

**Issue by lizhihonggithub** [StephenLee2016/Named_Entity_Recognition#1]
您好，我训练时，在以下语句出现异常
model = create_model(sess, Model, FLAGS.ckpt_path, load_word2vec, config, id_to_char, logger)
跟踪到
rnncell.py中
super(CoupledInputForgetGateLSTMCell, self).init(_reuse=reuse)
似乎是reuse设置问题
请问如何解决？谢谢！

**Comment by lizhihonggithub** [comment]
输出如下
Traceback (most recent call last):
  File "E:/ISE20170711/IseNre/Named_Entity_Recognition-master/main.py", line 228, in <module>
    if __name__ == "__main__":
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "E:/ISE20170711/IseNre/Named_Entity_Recognition-master/main.py", line 222, in main
    clean(FLAGS)
  File "E:/ISE20170711/IseNre/Named_Entity_Recognition-master/main.py", line 174, in train
    with tf.Session(config=tf_config) as sess:
  File "E:\ISE20170711\IseNre\Named_Entity_Recognition-master\utils.py", line 172, in create_model
    model = Model_class(config)
  File "E:\ISE20170711\IseNre\Named_Entity_Recognition-master\model.py", line 60, in __init__
    lstm_outputs = self.biLSTM_layer(lstm_inputs, self.lstm_dim, self.lengths)
  File "E:\ISE20170711\IseNre\Named_Entity_Recognition-master\model.py", line 126, in biLSTM_layer
    state_is_tuple=True)
  File "E:\ISE20170711\IseNre\Named_Entity_Recognition-master\rnncell.py", line 122, in __init__
    super(CoupledInputForgetGateLSTMCell, self).__init__(_reuse=reuse)
TypeError: object.__init__() takes no parameters

**Comment by lizhihonggithub** [comment]
It's fine now  。
